development:
  adapter: postgresql
  encoding: utf8
  database: hireme
  pool: 5
  username: hire
  password: Applying


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hireme
  pool: 5
  username: hire
  password: Applying

production:
  adapter: postgresql
  encoding: utf8
  database: hireme
  pool: 5
  username: hire
  password: Applying

cucumber:
  <<: *TEST
